# Generated by Django 4.2.11 on 2024-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='html_file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
