# Generated by Django 4.2.11 on 2024-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='html_file',
        ),
        migrations.AddField(
            model_name='product',
            name='html_file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
