# Generated by Django 4.2.11 on 2024-06-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_brand_html_file_product_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='html_file',
        ),
    ]
